---

- hosts: datacenter
  become: yes
  gather_facts: no

  tasks:
    - name: Override provided configuration with device configuration
      junipernetworks.junos.junos_l3_interfaces:
           config:
           - name: ge-0/0/0
             ipv4:
                     - address: "{{ip_address}}"
           state: replaced

    
